export const metadata = {
  title: "Starside Media - Privacy Policy",
  description:
    "Read Starside Media's privacy policy to understand how we handle your data.",
  images: [
    {
      url: "https://starside.media/StarsideLogoBlackCut.png",
      width: 1200,
      height: 630,
      alt: "Starside Media Logo - Privacy Policy",
    },
  ],
  url: "https://starside.media/privacy-policy",
};

export default function PrivacyPolicy() {
  return (
    <div className="max-w-5xl mx-auto py-8 px-4 md:py-32 md:px-8 text-foreground">
      <h1 className="text-4xl font-bold mb-4">Privacy Policy</h1>

      <p className="text-sm text-muted-foreground mb-8">
        Last updated: August 27, 2024
      </p>

      <p className="mb-6">
        This Privacy Policy describes our policies and procedures on the
        collection, use, and disclosure of your information when you use our
        service and tells you about your privacy rights and how the law protects
        you.
      </p>

      <h2 className="text-2xl font-semibold mb-4">
        Interpretation and Definitions
      </h2>

      <h3 className="text-xl font-semibold mb-3">Interpretation</h3>
      <p className="mb-6">
        The words of which the initial letter is capitalized have meanings
        defined under the following conditions. The following definitions shall
        have the same meaning regardless of whether they appear in singular or
        in plural.
      </p>

      <h3 className="text-xl font-semibold mb-3">Definitions</h3>
      <p className="mb-6">For the purposes of this Privacy Policy:</p>

      <ul className="list-disc list-inside mb-6 space-y-4">
        <li>
          <strong>Account</strong>: a unique account created for you to access
          our service or parts of our service.
        </li>
        <li>
          <strong>Affiliate</strong>: an entity that controls, is controlled by,
          or is under common control with a party, where "control" means
          ownership of 50% or more of the shares, equity interest, or other
          securities entitled to vote for election of directors or other
          managing authority.
        </li>
        <li>
          <strong>Company</strong> (referred to as either "the Company", "We",
          "Us" or "Our" in this Agreement): refers to Starside.
        </li>
        <li>
          <strong>Cookies</strong>: small files that are placed on your
          computer, mobile device, or any other device by a website, containing
          the details of your browsing history on that website among its many
          uses.
        </li>
        <li>
          <strong>Country</strong>: refers to Florida, United States.
        </li>
        <li>
          <strong>Device</strong>: any device that can access the service, such
          as a computer, a cellphone, or a digital tablet.
        </li>
        <li>
          <strong>Personal Data</strong>: any information that relates to an
          identified or identifiable individual.
        </li>
        <li>
          <strong>Service</strong>: refers to the website.
        </li>
        <li>
          <strong>Service Provider</strong>: any natural or legal person who
          processes the data on behalf of the Company. It refers to third-party
          companies or individuals employed by the Company to facilitate the
          service, to provide the service on behalf of the Company, to perform
          services related to the service, or to assist the Company in analyzing
          how the service is used.
        </li>
        <li>
          <strong>Usage Data</strong>: data collected automatically, either
          generated by the use of the service or from the service infrastructure
          itself (for example, the duration of a page visit).
        </li>
        <li>
          <strong>Website</strong>: refers to Starside, accessible from{" "}
          <a
            href="https://www.starside.media/"
            className="text-primary hover:underline"
            target="_blank"
            rel="noopener noreferrer"
          >
            https://www.starside.media/
          </a>
        </li>
        <li>
          <strong>You</strong>: the individual accessing or using the service,
          or the company, or other legal entity on behalf of which such
          individual is accessing or using the service, as applicable.
        </li>
      </ul>

      <h2 className="text-2xl font-semibold mb-4">
        Collecting and Using Your Personal Data
      </h2>

      <h3 className="text-xl font-semibold mb-3">Types of Data Collected</h3>
      <h4 className="text-lg font-medium mb-2">Personal Data</h4>
      <p className="mb-6">
        While using our service, we may ask you to provide us with certain
        personally identifiable information that can be used to contact or
        identify you. Personally identifiable information may include, but is
        not limited to:
      </p>

      <ul className="list-disc list-inside mb-6 space-y-4">
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Phone number</li>
        <li>Address, State, Province, ZIP/Postal code, City</li>
        <li>Usage Data</li>
      </ul>

      <h4 className="text-lg font-medium mb-2">Usage Data</h4>
      <p className="mb-6">
        Usage Data is collected automatically when using the service. Usage Data
        may include information such as your device's Internet Protocol address
        (e.g., IP address), browser type, browser version, the pages of our
        service that you visit, the time and date of your visit, the time spent
        on those pages, unique device identifiers, and other diagnostic data.
      </p>

      <h3 className="text-xl font-semibold mb-3">Use of Your Personal Data</h3>
      <p className="mb-6">
        The Company may use Personal Data for the following purposes:
      </p>

      <ul className="list-disc list-inside mb-6 space-y-4">
        <li>
          <strong>To provide and maintain our service</strong>, including to
          monitor the usage of our service.
        </li>
        <li>
          <strong>To manage your account:</strong> to manage your registration
          as a user of the service. The Personal Data you provide can give you
          access to different functionalities of the service that are available
          to you as a registered user.
        </li>
        <li>
          <strong>For the performance of a contract:</strong> the development,
          compliance, and undertaking of the purchase contract for the products,
          items, or services you have purchased or of any other contract with us
          through the service.
        </li>
        <li>
          <strong>To contact you:</strong> To contact you by email, telephone
          calls, SMS, or other equivalent forms of electronic communication,
          such as a mobile application's push notifications regarding updates or
          informative communications related to the functionalities, products,
          or contracted services, including the security updates, when necessary
          or reasonable for their implementation.
        </li>
        <li>
          <strong>To provide you</strong> with news, special offers, and general
          information about other goods, services, and events which we offer
          that are similar to those that you have already purchased or enquired
          about unless you have opted not to receive such information.
        </li>
        <li>
          <strong>To manage your requests:</strong> To attend and manage your
          requests to us.
        </li>
        <li>
          <strong>For business transfers:</strong> We may use your information
          to evaluate or conduct a merger, divestiture, restructuring,
          reorganization, dissolution, or other sale or transfer of some or all
          of our assets, whether as a going concern or as part of bankruptcy,
          liquidation, or similar proceeding, in which personal data held by us
          about our service users is among the assets transferred.
        </li>
        <li>
          <strong>For other purposes</strong>: We may use your information for
          other purposes, such as data analysis, identifying usage trends,
          determining the effectiveness of our promotional campaigns, and to
          evaluate and improve our service, products, services, marketing, and
          your experience.
        </li>
      </ul>

      <h3 className="text-xl font-semibold mb-3">
        Security of Your Personal Data
      </h3>
      <p className="mb-6">
        The security of your personal data is important to us, but remember that
        no method of transmission over the Internet, or method of electronic
        storage is 100% secure. While we strive to use commercially acceptable
        means to protect your personal data, we cannot guarantee its absolute
        security.
      </p>

      <h2 className="text-2xl font-semibold mb-4">
        Changes to this Privacy Policy
      </h2>
      <p className="mb-6">
        We may update our Privacy Policy from time to time. We will notify you
        of any changes by posting the new Privacy Policy on this page. We will
        let you know via email and/or a prominent notice on our service, prior
        to the change becoming effective and update the "Last updated" date at
        the top of this Privacy Policy.
      </p>

      <p className="mb-6">
        You are advised to review this Privacy Policy periodically for any
        changes. Changes to this Privacy Policy are effective when they are
        posted on this page.
      </p>

      <h2 className="text-2xl font-semibold mb-4">Contact Us</h2>
      <p className="mb-6">
        If you have any questions about this Privacy Policy, you can contact us:
      </p>

      <ul className="list-disc list-inside mb-6 space-y-4">
        <li>
          By email:{" "}
          <a
            href="mailto:seth@starside.media"
            className="text-primary hover:underline"
          >
            seth@starside.media
          </a>
        </li>
        <li>
          By visiting this page on our website:{" "}
          <a
            href="https://www.starside.media/contact"
            className="text-primary hover:underline"
            target="_blank"
            rel="noopener noreferrer"
          >
            https://www.starside.media/contact
          </a>
        </li>
      </ul>
    </div>
  );
}
